// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace kendo_northwind_pg.Data.Models;

public partial class DetailProduct
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public decimal? UnitPrice { get; set; }

    public short? UnitsInStock { get; set; }

    public string QuantityPerUnit { get; set; }

    public bool Discontinued { get; set; }

    public int? UnitsOnOrder { get; set; }

    public int? CategoryId { get; set; }

    public byte? CountryId { get; set; }

    public byte? CustomerRating { get; set; }

    public int? TargetSales { get; set; }

    public DateTime? LastSupply { get; set; }

    public virtual Category Category { get; set; }
}