// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace kendo_northwind_pg.Data.Models;

public partial class GanttResource
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Color { get; set; }
}