// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace kendo_northwind_pg.Data.Models;

public partial class GanttDependency
{
    public int Id { get; set; }

    public int PredecessorId { get; set; }

    public int SuccessorId { get; set; }

    public int Type { get; set; }
}