// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace kendo_northwind_pg.Data.Models;

public partial class GanttResourceAssignment
{
    public int Id { get; set; }

    public int TaskId { get; set; }

    public int ResourceId { get; set; }

    public double Units { get; set; }
}