// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace kendo_northwind_pg.Data.Models;

public partial class MeetingAttendee
{
    public int MeetingId { get; set; }

    public int AttendeeId { get; set; }

    public virtual Meeting Meeting { get; set; }
}