// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace kendo_northwind_pg.Data.Models;

public partial class OrgChartConnection
{
    public int Id { get; set; }

    public int? FromShapeId { get; set; }

    public int? ToShapeId { get; set; }

    public string Text { get; set; }

    public int? FromPointX { get; set; }

    public int? FromPointY { get; set; }

    public int? ToPointX { get; set; }

    public int? ToPointY { get; set; }
}