// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace kendo_northwind_pg.Data.Models;

public partial class Task
{
    public int TaskId { get; set; }

    public DateTime Start { get; set; }

    public DateTime End { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? OwnerId { get; set; }

    public bool IsAllDay { get; set; }

    public string RecurrenceRule { get; set; }

    public int? RecurrenceId { get; set; }

    public string RecurrenceException { get; set; }

    public string StartTimezone { get; set; }

    public string EndTimezone { get; set; }

    public virtual ICollection<Task> InverseRecurrence { get; set; } = new List<Task>();

    public virtual Task Recurrence { get; set; }
}