// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace kendo_northwind_pg.Data.Models;

public partial class UrbanArea
{
    public int Id { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public double Latitude { get; set; }

    public double Longitude { get; set; }

    public string CountryIso3 { get; set; }

    public int Pop1950 { get; set; }

    public int Pop1955 { get; set; }

    public int Pop1960 { get; set; }

    public int Pop1965 { get; set; }

    public int Pop1970 { get; set; }

    public int Pop1975 { get; set; }

    public int Pop1980 { get; set; }

    public int Pop1985 { get; set; }

    public int Pop1990 { get; set; }

    public int Pop1995 { get; set; }

    public int Pop2000 { get; set; }

    public int Pop2005 { get; set; }

    public int Pop2010 { get; set; }

    public int Pop2015 { get; set; }

    public int Pop2020 { get; set; }

    public int Pop2025 { get; set; }

    public int Pop2050 { get; set; }
}